theme: jekyll-theme-cayman
title: Matt Gagliano
description: Product Manager at Veritonic in NYC. Matt Gagliano designs and builds innovative digital products, services, and experiences through collaboration with diverse groups of people.
twitter:
  username: matttgagliano
social:
  name: Matt Gagliano
  links:
    - https://www.facebook.com/matttgagliano
    - https://www.linkedin.com/in/matttgagliano/
    - https://twitter.com/matttgagliano
    - https://www.instagram.com/matttgagliano/
    - https://github.com/mtgagliano
url: "https://www.mattgagliano.com"
    
# Plugins
gems:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-sitemap
  
paginate: 3
paginate_path: "/page:num/"

google_analytics: UA-114712624-1