theme: jekyll-theme-cayman
title: [Matt Gagliano]
permalink: /blog/:year/:month/:day/:title
description: [📍CT/NY  🏢 Product Manager @ <a href="https://www.veritonic.com" target="_blank">Veritonic</a>]
