title: Matt Gagliano
description: Designer and builder of digital things. Managing product remotely at Veritonic. Matt Gagliano enjoys working with diverse teams to create cool products, services, and experiences through new perspectives.
twitter:
  username: matttgagliano
social:
  name: Matt Gagliano
  links:
    - https://www.linkedin.com/in/matttgagliano/
    - https://twitter.com/matttgagliano
    - https://www.instagram.com/matttgagliano/
    - https://github.com/matttgagliano
url: "https://www.mattgagliano.com"
logo: /assets/img/mattgagliano.png

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-admin
  - jekyll-mentions

jekyll-mentions:
  base_url: https://twitter.com

paginate: 6
paginate_path: "/page:num/"

google_analytics: UA-114712624-1

permalink: pretty