theme: jekyll-theme-cayman
title: Matt Gagliano
description: Product Manager at Veritonic in NYC. Matt Gagliano designs and builds digital products, services, and experiences through collaboration with diverse groups of people, creating innovative applications from new ideas.
url: www.mattgagliano.com
twitter:
  username: matttgagliano
social:
  name: Matt Gagliano
  links:
    - https://www.facebook.com/matttgagliano
    - https://www.linkedin.com/in/matttgagliano/
    - https://twitter.com/matttgagliano
    - https://www.instagram.com/matttgagliano/
    - https://github.com/mtgagliano
    
# Plugins
gems:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  
paginate: 3
paginate_path: "/page:num/"