theme: jekyll-theme-cayman
title: Matt Gagliano
description: Matt Gagliano designs and builds digital products, services, and experiences in the NYC area through collaboration with diverse groups of people, creating innovative applications from new ideas.
    
# Plugins
gems:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  
paginate: 3
paginate_path: "/page:num/"