title: Matt Gagliano
description: Head of Product at Veritonic in NYC. Designer and builder of digital things. Matt Gagliano enjoys working with diverse groups of people to create cool products, services, and experiences through new perspectives.
twitter:
  username: matttgagliano
social:
  name: Matt Gagliano
  links:
    - https://www.facebook.com/matttgagliano
    - https://www.linkedin.com/in/matttgagliano/
    - https://twitter.com/matttgagliano
    - https://www.instagram.com/matttgagliano/
    - https://github.com/mtgagliano
url: "https://www.mattgagliano.com"
logo: /assets/img/propic.jpg

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

paginate: 6
paginate_path: "/page:num/"

google_analytics: UA-114712624-1
