theme: jekyll-theme-cayman
title: Matt Gagliano
description: Matt Gagliano is a tech enthusiast and product designer from the New York City area, writing about tech, design, and lifestyle news and topics.
    
# Plugins
gems:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  
paginate: 3
paginate_path: "/page:num/"